// var jmlRuangan = 7; 
// var noRuangan = 1;
// var kelasberfungsi = 4;
// for ( noRuangan; noRuangan <= jmlRuangan; noRuangan++ ) 
//     if (noRuangan <=4) {
//     console.log(`speaker di ruangan kelas ${noRuangan} berfungsi dengan baik`) 
   
// } else { 
//     console.log (`speaker di ruangan kelas ${noRuangan} tidak berfungsi dengan baik`)
// }

// let angka = prompt ('masukan angka')
// if (angka >= 85) {
//     alert("A");
// } else if (angka >= 70) {
//     alert ("B");
// } else if ( angka >= 55) {
//     alert ("C");
// }else if (angka < 55) {
//     alert ("D");
// }

 var jmlRuangan = 7; 
 var noRuangan = 1;
 var kelasberfungsi = 3;
 for ( noRuangan; noRuangan <= jmlRuangan; noRuangan++ ) 
    if (noRuangan <= 3) {
        console.log(`speaker di ruangan kelas ${noRuangan} berfungsi dengan baik`) 
   
    } else ( noRuangan =4 ) {
       console.log (`spekar diruangan kelas ${noRuangan} sedang diperbaiki`)
    } else { 
       console.log (`speaker di ruangan kelas ${noRuangan} tidak berfungsi dengan baik`)
    }
 
   